services:
  # PostgreSQL Database
  - type: pserv
    name: mayor-quiz-db
    env: docker
    plan: free
    ipAllowList: []

  # Web Service (Backend + Frontend)
  - type: web
    name: mayor-quiz-game
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mayor-quiz-db
          property: connectionString
    healthCheckPath: /api/health
